services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whisper-backend-dev
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - WHISPER_MODEL=base
      - CORS_ORIGINS=http://localhost:3050,http://127.0.0.1:3050
      - MAX_FILE_SIZE=104857600
    volumes:
      - ./backend:/app
      - /tmp:/tmp
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: whisper-frontend-dev
    ports:
      - "3050:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8050
      - VITE_PORT=5173
      - VITE_DEV_HOST=0.0.0.0
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 5173

networks:
  default:
    name: whisper-network-dev